<a href="https://colab.research.google.com/github/shivapri/assignment1wt/blob/master/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import gym
import numpy as np
import time

env = gym.make('FrozenLake-v0')
STATES = env.observation_space.n
ACTIONS = env.action_space.n

Q = np.zeros((STATES, ACTIONS))

EPISODES = 1500 
MAX_STEPS = 100  
LEARNING_RATE = 0.81  
GAMMA = 0.96

RENDER = False 

epsilon = 0.9
rewards = []
for episode in range(EPISODES):

  state = env.reset()
  for _ in range(MAX_STEPS):
    
    if RENDER:
      env.render()

    if np.random.uniform(0, 1) < epsilon:
      action = env.action_space.sample()  
    else:
      action = np.argmax(Q[state, :])

    next_state, reward, done, _ = env.step(action)

    Q[state, action] = Q[state, action] + LEARNING_RATE * (reward + GAMMA * np.max(Q[next_state, :]) - Q[state, action])

    state = next_state

    if done: 
      rewards.append(reward)
      epsilon -= 0.001
      break  

print(Q)
print(f"Average reward: {sum(rewards)/len(rewards)}:")

[[3.57824901e-01 5.14548764e-02 5.02114305e-02 4.57632634e-02]
 [2.01921867e-03 1.18557718e-02 7.40568869e-03 1.49972734e-01]
 [2.23260062e-02 2.30817260e-02 9.10585292e-03 1.22550095e-01]
 [7.48481735e-03 1.59252648e-02 2.81092521e-04 1.09962881e-01]
 [4.42496211e-01 4.33683590e-02 2.53753711e-03 1.61195617e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.88293028e-03 1.32982499e-04 1.99388839e-04 8.31512231e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.46490157e-02 3.64042967e-03 2.35478840e-02 5.66081837e-01]
 [8.79133115e-04 2.46091450e-01 2.46474410e-02 2.33466783e-02]
 [7.94176027e-01 6.55407333e-03 6.23905088e-03 1.62630567e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.47401175e-02 7.13980431e-02 8.14306723e-01 3.23371354e-02]
 [1.97034463e-01 9.90339675e-01 2.06907184e-01 2.33219730e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000